### ISSUE TITLE
Git tag latest releases

### ISSUE THREAD

**Issue by emanuelb** [TBCode523/Crypto-Testnet-Wallet#1]
Latest release on google play is version: 1.0 Updated: March 28, 2021
https://play.google.com/store/apps/details?id=tbcode.example.kotlinbitcoinwallet

Git tag releases as currently the repo has no git tags: https://github.com/TBCode523/Bitcoin-Testnet-Wallet/tags

**Comment by TBCode523** [comment]
Thanks for bringing this to my attention I haven't had time to work on this app due to college so I really appreciate you reminding me. I just put the first release and an v1.0.1 will be live either 2morrow or sometime early this week!
